apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anjali-app
  namespace: argocd

spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source: 
    repoURL: https://github.com/anjivish12/ArgocdProject.git
    path: .
    ref: main
  syncPolicy:
    automated:
      enabled: true
      
    