apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: myapp
    app1: myapp1
    app2: myapp2
spec:
  containers:
    - name: nginxcon
      image: nginx
      ports:
        - containerPort: 80

