apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: myapp
spec:
  containers:
    - name: nginxcon
      image: nginx
      ports:
        - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: myapp
spec:
  containers:
    - name: frontendcon
      image: anjalivish12/elearnrepo
      ports:
        - containerPort: 3001